
CREATE OR REPLACE PROCEDURE ${tenant_transfm_db_name}.${tenant_transfm_schema_name}.PRC_LS_DB_COUNTRY_REGION()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
DECLARE

CURRENT_TS_VAR TIMESTAMP;

BEGIN 

TRUNCATE TABLE ${tenant_transfm_db_name}.${tenant_transfm_schema_name}.LS_DB_COUNTRY_REGION;

INSERT INTO ${tenant_transfm_db_name}.${tenant_transfm_schema_name}.LS_DB_COUNTRY_REGION(COUNTRY_NAME, COUNTRY_ISO_ALPHA2, COUNTRY_ISO_ALPHA3, REGION_NAME, CODE)
select 'NORWAY' COUNTRY_NAME, 'NO' COUNTRY_ISO_ALPHA2, 'NOR' COUNTRY_ISO_ALPHA3, 'EEA' REGION_NAME, 'NO' CODE
union all select 'CONGO', 'CG', 'COG', 'ROW', 'CG'
union all select 'BOLIVIA, PLURINATIONAL STATE OF', 'BO', 'BOL', 'ROW', 'BO'
union all select 'JAMAICA', 'JM', 'JAM', 'ROW', 'JM'
union all select 'KYRGYZSTAN', 'KG', 'KGZ', 'ROW', 'KG'
union all select 'ISLE OF MAN', 'IM', 'IMN', 'ROW', 'IM'
union all select 'MOZAMBIQUE', 'MZ', 'MOZ', 'ROW', 'MZ'
union all select 'GHANA', 'GH', 'GHA', 'ROW', 'GH'
union all select 'CABO VERDE', 'CV', 'CPV', 'ROW', 'CV'
union all select 'PITCAIRN', 'PN', 'PCN', 'ROW', 'PN'
union all select 'SAINT KITTS AND NEVIS', 'KN', 'KNA', 'ROW', 'KN'
union all select 'TIMOR-LESTE', 'TL', 'TLS', 'ROW', 'TL'
union all select 'MAYOTTE', 'YT', 'MYT', 'ROW', 'YT'
union all select 'SLOVENIA', 'SI', 'SVN', 'EEA', 'SI'
union all select 'PANAMA', 'PA', 'PAN', 'ROW', 'PA'
union all select 'BELGIUM', 'BE', 'BEL', 'EEA', 'BE'
union all select 'COCOS (KEELING ISLANDS', 'CC', 'CCK', 'ROW', 'CC'
union all select 'BULGARIA', 'BG', 'BGR', 'EEA', 'BG'
union all select 'KENYA', 'KE', 'KEN', 'ROW', 'KE'
union all select 'SOUTH AFRICA', 'ZA', 'ZAF', 'ROW', 'ZA'
union all select 'HUNGARY', 'HU', 'HUN', 'EEA', 'HU'
union all select 'FAROE ISLANDS', 'FO', 'FRO', 'ROW', 'FO'
union all select 'CHAD', 'TD', 'TCD', 'ROW', 'TD'
union all select 'ALGERIA', 'DZ', 'DZA', 'ROW', 'DZ'
union all select 'ANGOLA', 'AO', 'AGO', 'ROW', 'AO'
union all select 'SENEGAL', 'SN', 'SEN', 'ROW', 'SN'
union all select 'MALTA', 'MT', 'MLT', 'EEA', 'MT'
union all select 'SAN MARINO', 'SM', 'SMR', 'ROW', 'SM'
union all select 'CZECHIA', 'CZ', 'CZE', 'EEA', 'CZ'
union all select 'PALAU', 'PW', 'PLW', 'ROW', 'PW'
union all select 'MALDIVES', 'MV', 'MDV', 'ROW', 'MV'
union all select 'MOROCCO', 'MA', 'MAR', 'ROW', 'MA'
union all select 'SAO TOME AND PRINCIPE', 'ST', 'STP', 'ROW', 'ST'
union all select 'POLAND', 'PL', 'POL', 'EEA', 'PL'
union all select 'ANGUILLA', 'AI', 'AIA', 'ROW', 'AI'
union all select 'BERMUDA', 'BM', 'BMU', 'ROW', 'BM'
union all select 'NIUE', 'NU', 'NIU', 'ROW', 'NU'
union all select 'MACAO', 'MO', 'MAC', 'ROW', 'MO'
union all select 'NETHERLANDS ANTILLES',NULL,NULL, 'ROW',NULL
union all select 'SAMOA', 'WS', 'WSM', 'ROW', 'WS'
union all select 'JERSEY', 'JE', 'JEY', 'ROW', 'JE'
union all select 'MONTENEGRO', 'ME', 'MNE', 'ROW', 'ME'
union all select 'GREENLAND', 'GL', 'GRL', 'ROW', 'GL'
union all select 'BOTSWANA', 'BW', 'BWA', 'ROW', 'BW'
union all select 'GAMBIA', 'GM', 'GMB', 'ROW', 'GM'
union all select 'PUERTO RICO', 'PR', 'PRI', 'ROW', 'PR'
union all select 'KUWAIT', 'KW', 'KWT', 'ROW', 'KW'
union all select 'IRAQ', 'IQ', 'IRQ', 'ROW', 'IQ'
union all select 'ESWATINI', 'SZ', 'SWZ', 'ROW', 'SZ'
union all select 'UNITED STATES OF AMERICA', 'US', 'USA', 'USA + CANADA', 'US'
union all select 'THAILAND', 'TH', 'THA', 'ROW', 'TH'
union all select 'LIBERIA', 'LR', 'LBR', 'ROW', 'LR'
union all select 'ZIMBABWE', 'ZW', 'ZWE', 'ROW', 'ZW'
union all select 'TURKMENISTAN', 'TM', 'TKM', 'ROW', 'TM'
union all select 'ZAIRE',NULL,NULL, 'ROW',NULL
union all select 'QATAR', 'QA', 'QAT', 'ROW', 'QA'
union all select 'SRI LANKA', 'LK', 'LKA', 'ROW', 'LK'
union all select 'GUINEA', 'GN', 'GIN', 'ROW', 'GN'
union all select 'LATVIA', 'LV', 'LVA', 'EEA', 'LV'
union all select 'ITALY', 'IT', 'ITA', 'EEA', 'IT'
union all select 'CHILE', 'CL', 'CHL', 'ROW', 'CL'
union all select 'GABON', 'GA', 'GAB', 'ROW', 'GA'
union all select 'MAURITANIA', 'MR', 'MRT', 'ROW', 'MR'
union all select 'COLOMBIA', 'CO', 'COL', 'ROW', 'CO'
union all select 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM', 'HMD', 'ROW', 'HM'
union all select 'MARTINIQUE', 'MQ', 'MTQ', 'ROW', 'MQ'
union all select 'RUSSIAN FEDERATION', 'RU', 'RUS', 'ROW', 'RU'
union all select 'GUYANA', 'GY', 'GUY', 'ROW', 'GY'
union all select 'PAPUA NEW GUINEA', 'PG', 'PNG', 'ROW', 'PG'
union all select 'ICELAND', 'IS', 'ISL', 'EEA', 'IS'
union all select 'ARGENTINA', 'AR', 'ARG', 'ROW', 'AR'
union all select 'COTE D''IVOIRE', 'CI', 'CIV', 'ROW', 'CI'
union all select 'CUBA', 'CU', 'CUB', 'ROW', 'CU'
union all select 'PALESTINE, STATE OF', 'PS', 'PSE', 'ROW', 'PS'
union all select 'HONG KONG', 'HK', 'HKG', 'ROW', 'HK'
union all select 'MAURITIUS', 'MU', 'MUS', 'ROW', 'MU'
union all select 'BAHAMAS', 'BS', 'BHS', 'ROW', 'BS'
union all select 'HOLY SEE', '-', '-', 'ROW', 'VA'
union all select 'GUERNSEY', 'GG', 'GGY', 'ROW', 'GG'
union all select 'LITHUANIA', 'LT', 'LTU', 'EEA', 'LT'
union all select 'FINLAND', 'FI', 'FIN', 'EEA', 'FI'
union all select 'GUADELOUPE', 'GP', 'GLP', 'ROW', 'GP'
union all select 'NAMIBIA', 'NA', 'NAM', 'ROW', 'NA'
union all select 'URUGUAY', 'UY', 'URY', 'ROW', 'UY'
union all select 'TUNISIA', 'TN', 'TUN', 'ROW', 'TN'
union all select 'DOMINICAN REPUBLIC', 'DO', 'DOM', 'ROW', 'DO'
union all select 'CONGO, DEMOCRATIC REPUBLIC OF THE', 'CD', 'COD', 'ROW', 'CD'
union all select 'ANTARCTICA', 'AQ', 'ATA', 'ROW', 'AQ'
union all select 'TONGA', 'TO', 'TON', 'ROW', 'TO'
union all select 'TANZANIA, UNITED REPUBLIC OF', 'TZ', 'TZA', 'ROW', 'TZ'
union all select 'SPAIN', 'ES', 'ESP', 'EEA', 'ES'
union all select 'IRELAND', 'IE', 'IRL', 'EEA', 'IE'
union all select 'SERBIA AND MONTENEGRO',NULL,NULL, 'ROW',NULL
union all select 'COSTA RICA', 'CR', 'CRI', 'ROW', 'CR'
union all select 'SAINT MARTIN, FRENCH PART', '-', '-', 'ROW', 'MF'
union all select 'BHUTAN', 'BT', 'BTN', 'ROW', 'BT'
union all select 'SOMALIA', 'SO', 'SOM', 'ROW', 'SO'
union all select 'OMAN', 'OM', 'OMN', 'ROW', 'OM'
union all select 'JAPAN', 'JP', 'JPN', 'JAPAN', 'JP'
union all select 'MALAWI', 'MW', 'MWI', 'ROW', 'MW'
union all select 'SURINAME', 'SR', 'SUR', 'ROW', 'SR'
union all select 'ISRAEL', 'IL', 'ISR', 'ROW', 'IL'
union all select 'FRENCH SOUTHERN TERRITORIES', 'TF', 'ATF', 'ROW', 'TF'
union all select 'REUNION', 'RE', 'REU', 'ROW', 'RE'
union all select 'TURKS AND CAICOS ISLANDS', 'TC', 'TCA', 'ROW', 'TC'
union all select 'AUSTRIA', 'AT', 'AUT', 'EEA', 'AT'
union all select 'GERMANY', 'DE', 'DEU', 'EEA', 'DE'
union all select 'GIBRALTAR', 'GI', 'GIB', 'ROW', 'GI'
union all select 'IRAN, ISLAMIC REPUBLIC OF', 'IR', 'IRN', 'ROW', 'IR'
union all select 'WALLIS AND FUTUNA', 'WF', 'WLF', 'ROW', 'WF'
union all select 'GEORGIA', 'GE', 'GEO', 'ROW', 'GE'
union all select 'NEPAL', 'NP', 'NPL', 'ROW', 'NP'
union all select 'UGANDA', 'UG', 'UGA', 'ROW', 'UG'
union all select 'BRUNEI DARUSSALAM', 'BN', 'BRN', 'ROW', 'BN'
union all select 'JORDAN', 'JO', 'JOR', 'ROW', 'JO'
union all select 'EAST TIMOR',NULL,NULL, 'ROW',NULL
union all select 'COOK ISLANDS', 'CK', 'COK', 'ROW', 'CK'
union all select 'MONACO', 'MC', 'MCO', 'ROW', 'MC'
union all select 'NORTHERN MARIANA ISLANDS', 'MP', 'MNP', 'ROW', 'MP'
union all select 'TUVALU', 'TV', 'TUV', 'ROW', 'TV'
union all select 'ROMANIA', 'RO', 'ROU', 'EEA', 'RO'
union all select 'PORTUGAL', 'PT', 'PRT', 'EEA', 'PT'
union all select 'DOMINICA', 'DM', 'DMA', 'ROW', 'DM'
union all select 'ANDORRA', 'AD', 'AND', 'ROW', 'AD'
union all select 'AZERBAIJAN', 'AZ', 'AZE', 'ROW', 'AZ'
union all select 'UKRAINE', 'UA', 'UKR', 'ROW', 'UA'
union all select 'NEW CALEDONIA', 'NC', 'NCL', 'ROW', 'NC'
union all select 'SAINT PIERRE AND MIQUELON', '-', '-', 'ROW', 'PM'
union all select 'INDIA', 'IN', 'IND', 'ROW', 'IN'
union all select 'BAHRAIN', 'BH', 'BHR', 'ROW', 'BH'
union all select 'NETHERLANDS', 'NL', 'NLD', 'EEA', 'NL'
union all select 'ALAND ISLANDS', 'AX', 'ALA', 'ROW', 'AX'
union all select 'MOLDOVA, REPUBLIC OF', 'MD', 'MDA', 'ROW', 'MD'
union all select 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'KP', 'PRK', 'ROW', 'KP'
union all select 'TURKEY',NULL,NULL, 'ROW',NULL
union all select 'TOKELAU', 'TK', 'TKL', 'ROW', 'TK'
union all select 'TAIWAN', 'TW', 'TWN', 'Emerging Markets-ROPU TCM', 'TW'
union all select 'RWANDA', 'RW', 'RWA', 'ROW', 'RW'
union all select 'ZAMBIA', 'ZM', 'ZMB', 'ROW', 'ZM'
union all select 'NIGER', 'NE', 'NER', 'ROW', 'NE'
union all select 'AMERICAN SAMOA', 'AS', 'ASM', 'ROW', 'AS'
union all select 'CAMEROON', 'CM', 'CMR', 'ROW', 'CM'
union all select 'GRENADA', 'GD', 'GRD', 'ROW', 'GD'
union all select 'SWEDEN', 'SE', 'SWE', 'EEA', 'SE'
union all select 'YUGOSLAVIA',NULL,NULL, 'ROW',NULL
union all select 'KOREA, REPUBLIC OF', 'KR', 'KOR', 'ROW', 'KR'
union all select 'BURUNDI', 'BI', 'BDI', 'ROW', 'BI'
union all select 'PAKISTAN', 'PK', 'PAK', 'ROW', 'PK'
union all select 'FIJI', 'FJ', 'FJI', 'ROW', 'FJ'
union all select 'CENTRAL AFRICAN REPUBLIC', 'CF', 'CAF', 'ROW', 'CF'
union all select 'SUDAN', 'SD', 'SDN', 'ROW', 'SD'
union all select 'ARUBA', 'AW', 'ABW', 'ROW', 'AW'
union all select 'SAINT VINCENT AND THE GRENADINES', 'VC', 'VCT', 'ROW', 'VC'
union all select 'NICARAGUA', 'NI', 'NIC', 'ROW', 'NI'
union all select 'FRANCE', 'FR', 'FRA', 'EEA', 'FR'
union all select 'HAITI', 'HT', 'HTI', 'ROW', 'HT'
union all select 'ERITREA', 'ER', 'ERI', 'ROW', 'ER'
union all select 'MONTSERRAT', 'MS', 'MSR', 'ROW', 'MS'
union all select 'EGYPT', 'EG', 'EGY', 'ROW', 'EG'
union all select 'NEW ZEALAND', 'NZ', 'NZL', 'ROW', 'NZ'
union all select 'TRINIDAD AND TOBAGO', 'TT', 'TTO', 'ROW', 'TT'
union all select 'PARAGUAY', 'PY', 'PRY', 'ROW', 'PY'
union all select 'CAYMAN ISLANDS', 'KY', 'CYM', 'ROW', 'KY'
union all select 'NAURU', 'NR', 'NRU', 'ROW', 'NR'
union all select 'BONAIRE, SINT EUSTATIUS AND SABA', 'BQ', 'BES', 'ROW', 'BQ'
union all select 'LEBANON', 'LB', 'LBN', 'ROW', 'LB'
union all select 'MALI', 'ML', 'MLI', 'ROW', 'ML'
union all select 'VANUATU', 'VU', 'VUT', 'ROW', 'VU'
union all select 'BENIN', 'BJ', 'BEN', 'ROW', 'BJ'
union all select 'EQUATORIAL GUINEA', 'GQ', 'GNQ', 'ROW', 'GQ'
union all select 'BANGLADESH', 'BD', 'BGD', 'ROW', 'BD'
union all select 'LIECHTENSTEIN', 'LI', 'LIE', 'EEA', 'LI'
union all select 'FRENCH GUIANA', 'GF', 'GUF', 'ROW', 'GF'
union all select 'NORFOLK ISLAND', 'NF', 'NFK', 'ROW', 'NF'
union all select 'INDONESIA', 'ID', 'IDN', 'ROW', 'ID'
union all select 'SAUDI ARABIA', 'SA', 'SAU', 'ROW', 'SA'
union all select 'COMOROS', 'KM', 'COM', 'ROW', 'KM'
union all select 'MEXICO', 'MX', 'MEX', 'ROW', 'MX'
union all select 'MICRONESIA, FEDERATED STATES OF', 'FM', 'FSM', 'ROW', 'FM'
union all select 'ETHIOPIA', 'ET', 'ETH', 'ROW', 'ET'
union all select 'LESOTHO', 'LS', 'LSO', 'ROW', 'LS'
union all select 'BRITISH INDIAN OCEAN TERRITORY', 'IO', 'IOT', 'ROW', 'IO'
union all select 'SAINT BARTHELEMY', '-', '-', 'ROW', 'BL'
union all select 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', '-', '-', 'ROW', 'GS'
union all select 'NORTH MACEDONIA', 'MK', 'MKD', 'ROW', 'MK'
union all select 'BURKINA FASO', 'BF', 'BFA', 'ROW', 'BF'
union all select 'FRANCE, METROPOLITAN',NULL,NULL, 'EEA',NULL
union all select 'SVALBARD AND JAN MAYEN', '-', '-', 'ROW', 'SJ'
union all select 'KAZAKHSTAN', 'KZ', 'KAZ', 'ROW', 'KZ'
union all select 'MONGOLIA', 'MN', 'MNG', 'ROW', 'MN'
union all select 'CROATIA', 'HR', 'HRV', 'EEA', 'HR'
union all select 'VIRGIN ISLANDS, U.S.', 'VI', 'VIR', 'ROW', 'VI'
union all select 'ARMENIA', 'AM', 'ARM', 'ROW', 'AM'
union all select 'UNITED STATES MINOR OUTLYING ISLANDS', 'UM', 'UMI', 'ROW', 'UM'
union all select 'TOGO', 'TG', 'TGO', 'ROW', 'TG'
union all select 'SERBIA', 'RS', 'SRB', 'ROW', 'RS'
union all select 'MADAGASCAR', 'MG', 'MDG', 'ROW', 'MG'
union all select 'LUXEMBOURG', 'LU', 'LUX', 'EEA', 'LU'
union all select 'BOUVET ISLAND', 'BV', 'BVT', 'ROW', 'BV'
union all select 'SOUTH SUDAN', 'SS', 'SSD', 'ROW', 'SS'
union all select 'NIGERIA', 'NG', 'NGA', 'ROW', 'NG'
union all select 'UNITED KINGDOM(NORTHERN IRELAND)',NULL,NULL, 'EEA',NULL
union all select 'WESTERN SAHARA', 'EH', 'ESH', 'ROW', 'EH'
union all select 'FALKLAND ISLANDS (MALVINAS', 'FK', 'FLK', 'ROW', 'FK'
union all select 'UNITED ARAB EMIRATES', 'AE', 'ARE', 'ROW', 'AE'
union all select 'SINGAPORE', 'SG', 'SGP', 'ROW', 'SG'
union all select 'KIRIBATI', 'KI', 'KIR', 'ROW', 'KI'
union all select 'ECUADOR', 'EC', 'ECU', 'ROW', 'EC'
union all select 'BELIZE', 'BZ', 'BLZ', 'ROW', 'BZ'
union all select 'DENMARK', 'DK', 'DNK', 'EEA', 'DK'
union all select 'VENEZUELA, BOLIVARIAN REPUBLIC OF', 'VE', 'VEN', 'ROW', 'VE'
union all select 'AUSTRALIA', 'AU', 'AUS', 'ROW', 'AU'
union all select 'ESTONIA', 'EE', 'EST', 'EEA', 'EE'
union all select 'SLOVAKIA', 'SK', 'SVK', 'EEA', 'SK'
union all select 'CHRISTMAS ISLAND', 'CX', 'CXR', 'ROW', 'CX'
union all select 'CAMBODIA', 'KH', 'KHM', 'ROW', 'KH'
union all select 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', '-', '-', 'ROW', 'SH'
union all select 'FRENCH POLYNESIA', 'PF', 'PYF', 'ROW', 'PF'
union all select 'SINT MAARTEN (DUTCH PART', 'SX', 'SXM', 'ROW', 'SX'
union all select 'GREECE', 'GR', 'GRC', 'EEA', 'GR'
union all select 'SIERRA LEONE', 'SL', 'SLE', 'ROW', 'SL'
union all select 'CANADA', 'CA', 'CAN', 'USA + CANADA', 'CA'
union all select 'DJIBOUTI', 'DJ', 'DJI', 'ROW', 'DJ'
union all select 'BRAZIL', 'BR', 'BRA', 'ROW', 'BR'
union all select 'BRITISH VIRGIN ISLANDS', 'VG', 'VGB', 'ROW', 'VG'
union all select 'GUINEA-BISSAU', 'GW', 'GNB', 'ROW', 'GW'
union all select 'EL SALVADOR', 'SV', 'SLV', 'ROW', 'SV'
union all select 'BOSNIA and HERZEGOVINA', 'BA', 'BIH', 'ROW', 'BA'
union all select 'MARSHALL ISLANDS', 'MH', 'MHL', 'ROW', 'MH'
union all select 'SWITZERLAND', 'CH', 'CHE', 'ROW', 'CH'
union all select 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LA', 'LAO', 'ROW', 'LA'
union all select 'UZBEKISTAN', 'UZ', 'UZB', 'ROW', 'UZ'
union all select 'SEYCHELLES', 'SC', 'SYC', 'ROW', 'SC'
union all select 'SYRIAN ARAB REPUBLIC', 'SY', 'SYR', 'ROW', 'SY'
union all select 'SAINT LUCIA', 'LC', 'LCA', 'ROW', 'LC'
union all select 'ALBANIA', 'AL', 'ALB', 'ROW', 'AL'
union all select 'ANTIGUA AND BARBUDA', 'AG', 'ATG', 'ROW', 'AG'
union all select 'LIBYA', 'LY', 'LBY', 'ROW', 'LY'
union all select 'PERU', 'PE', 'PER', 'ROW', 'PE'
union all select 'VIETNAM', 'VN', 'VNM', 'ROW', 'VN'
union all select 'CYPRUS', 'CY', 'CYP', 'EEA', 'CY'
union all select 'MALAYSIA', 'MY', 'MYS', 'ROW', 'MY'
union all select 'TAJIKISTAN', 'TJ', 'TJK', 'ROW', 'TJ'
union all select 'BARBADOS', 'BB', 'BRB', 'ROW', 'BB'
union all select 'PHILIPPINES', 'PH', 'PHL', 'ROW', 'PH'
union all select 'GUAM', 'GU', 'GUM', 'ROW', 'GU'
union all select 'GUATEMALA', 'GT', 'GTM', 'ROW', 'GT'
union all select 'CURAÇAO', 'CW', 'CUW', 'ROW', 'CW'
union all select 'AFGHANISTAN', 'AF', 'AFG', 'ROW', 'AF'
union all select 'BELARUS', 'BY', 'BLR', 'ROW', 'BY'
union all select 'MYANMAR', 'MM', 'MMR', 'ROW', 'MM'
union all select 'CHINA', 'CN', 'CHN', 'ROW', 'CN'
union all select 'HONDURAS', 'HN', 'HND', 'ROW', 'HN'
union all select 'SOLOMON ISLANDS', 'SB', 'SLB', 'ROW', 'SB'
union all select 'YEMEN', 'YE', 'YEM', 'ROW', 'YE'
 ;


 RETURN 'LS_DB_COUNTRY_REGION Update completed';

EXCEPTION
  WHEN OTHER THEN
    LET LINE := SQLCODE || ': ' || SQLERRM;
UPDATE ${tenant_transfm_db_name}.${tenant_transfm_schema_name}.LS_DB_DATA_PROCESSING_DTL_TBL set ERROR_DETAILS=:line,LOAD_STATUS = 'Error' WHERE target_table_name='LS_DB_COUNTRY_REGION'
and LOAD_STATUS = 'In Progress'
;


  RETURN 'LS_DB_COUNTRY_REGION not loaded due to etl error. please check LS_DB_DATA_PROCESSING_DTL_TBL for more details';
END;
$$
;