/*
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_MIN_THERAPY_START_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_MAX_THERAPY_END_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_END_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_START_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_TIME_OFF_DRUG_NORMAL TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_TREATMENT_DURATION_NORMAL TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_PERIOD_CONCAT TEXT;


call $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY_DER();
*/

	
-- USE SCHEMA $$TGT_DB_NAME.$$LSDB_TRANSFM;
CREATE OR REPLACE PROCEDURE $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY_DER()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
DECLARE

CURRENT_TS_VAR TIMESTAMP;

BEGIN 

CURRENT_TS_VAR := CURRENT_TIMESTAMP();


-- delete from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG  where TARGET_TABLE_NAME='LS_DB_DRUG_THERAPY_DER';
-- delete from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL  where TARGET_TABLE_NAME='LS_DB_DRUG_THERAPY_DER';
/*
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_MIN_THERAPY_START_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_MAX_THERAPY_END_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_END_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_START_DATE TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_TIME_OFF_DRUG_NORMAL TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_TREATMENT_DURATION_NORMAL TEXT;
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY ADD COLUMN DER_THERAPY_PERIOD_CONCAT TEXT;
*/






insert into $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG (ROW_WID,TARGET_TABLE_NAME,PARAM_NAME)

select ROW_WID,TARGET_TABLE_NAME,PARAM_NAME from 
(select coalesce((select max( ROW_WID) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)+1,1) ROW_WID,'LS_DB_DRUG_THERAPY_DER' AS TARGET_TABLE_NAME,'CDC_EXTRACT_TS_LB' PARAM_NAME
 union all select coalesce((select max( ROW_WID) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)+2,1),'LS_DB_DRUG_THERAPY_DER','CDC_EXTRACT_TS_UB'
) where TARGET_TABLE_NAME not in (select TARGET_TABLE_NAME from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)
;

INSERT INTO $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL(ROW_WID,FUNCTIONAL_AREA,ENTITY_NAME,TARGET_TABLE_NAME,LOAD_TS,LOAD_START_TS,LOAD_END_TS,
REC_READ_CNT,REC_PROCESSED_CNT,ERROR_REC_CNT,ERROR_DETAILS,LOAD_STATUS,CHANGED_REC_SET
)
SELECT (select nvl(max(row_wid)+1,1) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRUG_THERAPY_DER'),
	'LSRA','Case','LS_DB_DRUG_THERAPY_DER',null,:CURRENT_TS_VAR,null,null,null,null,null,'In Progress',null;


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= nvl((SELECT LOAD_TS from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL 
						WHERE TARGET_TABLE_NAME='LS_DB_DRUG_THERAPY_DER' 
						AND LOAD_STATUS = 'Completed' ORDER BY ROW_WID DESC limit 1),to_timestamp('1900-01-01','YYYY-MM-DD'))
WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_THERAPY_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_LB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= (select max(load_ts) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY)
WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_THERAPY_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_UB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;

DROP TABLE IF EXISTS $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC;
CREATE TEMPORARY TABLE  $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC AS
select distinct dgth_ari_rec_id as ari_rec_id
FROM 
	$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY 
	
	where load_ts > (SELECT PARAM_VALUE FROM 
$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_THERAPY_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_LB')  and

load_ts <=  (SELECT PARAM_VALUE FROM 
$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_THERAPY_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_UB') AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
;	


/*( select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED
		)*/


DROP TABLE IF EXISTS $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED;
CREATE TEMPORARY TABLE  $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED AS
select LSMV_DRUG.ARI_REC_ID||'-'||AD.SEQ_PRODUCT AS UNBLINDED_REC
				from 
				(
				SELECT LSMV_DRUG.ARI_REC_ID,
					BLINDED_PRODUCT_REC_ID,
					row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank
				FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
				AND   CDC_OPERATION_TYPE IN ('I','U') 
				) LSMV_DRUG 
				JOIN
				(
				SELECT LSMV_DRUG.ARI_REC_ID,
					LSMV_DRUG.RECORD_ID AS SEQ_PRODUCT,
					row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank
				FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
				AND   CDC_OPERATION_TYPE IN ('I','U') 
				) AD
				ON LSMV_DRUG.ARI_REC_ID              = AD.ARI_REC_ID
				AND LSMV_DRUG.BLINDED_PRODUCT_REC_ID = AD.SEQ_PRODUCT
				AND LSMV_DRUG.rank=1 AND AD.rank=1

;





UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_MIN_THERAPY_START_DATE=LS_DB_DRUG_THERAPY_TMP.DER_MIN_THERAPY_START_DATE   

FROM (
SELECT ARI_REC_ID,DER_MIN_THERAPY_START_DATE
FROM
  (SELECT AP.ARI_REC_ID,
    AP.RECORD_ID,
    AP.RANK_ORDER ,
    'D'
    ||AP.RANK_ORDER
    ||': '
    ||
	CASE WHEN APT.DER_MIN_THERAPY IS NULL 
	THEN '-'
	ELSE UPPER(APT.DER_MIN_THERAPY)
	END AS DER_MIN_THERAPY_START_DATE
  FROM (select ARI_REC_ID,
    RECORD_ID,
    RANK_ORDER,DRUGCHARACTERIZATION,
	row_number() over (partition by ARI_REC_ID order by CDC_OPERATION_TIME desc) rank
	FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where  
		ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
    and CDC_OPERATION_TYPE IN ('I','U')) AP LEFT JOIN
    (SELECT dgth_ARI_REC_ID,dgth_FK_AD_REC_ID AS SEQ_PRODUCT,
	CASE
       WHEN dgth_DRUGSTARTDATEFMT IS NULL  THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-MON-YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (0,102)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-MON-YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (1,602)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (2,610)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'MON-YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (3,4,5,6,7,8,9,204,611,203)       THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-MON-YYYY')
     END DER_MIN_THERAPY
    FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY
    WHERE dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
	and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
	and 
	(dgth_ARI_REC_ID,dgth_FK_AD_REC_ID,dgth_DRUGSTARTDATE) IN
		(select LS_DB_DRUG_THERAPY.dgth_ARI_REC_ID,
			LS_DB_DRUG_THERAPY.dgth_FK_AD_REC_ID,	
			MIN(LS_DB_DRUG_THERAPY.dgth_DRUGSTARTDATE) As MIN_START_THERAPY_DATE
			FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY 
			where dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
			and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
		group by 1,2
      )
    ) APT ON  AP.DRUGCHARACTERIZATION IN ('1','3')
  AND AP.ARI_REC_ID        =APT.dgth_ARI_REC_ID
  AND AP.RECORD_ID   =APT.SEQ_PRODUCT
  where rank=1 and AP.ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
  AND  AP.ARI_REC_ID||'-'||AP.RECORD_ID NOT IN
    (select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED) 
  )
ORDER BY ARI_REC_ID,
  RANK_ORDER
) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.ari_rec_id	
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM'); 

--- DERIVED_MAX_THERAPY_END_DATE

UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_MAX_THERAPY_END_DATE=LS_DB_DRUG_THERAPY_TMP.DER_MAX_THERAPY_END_DATE   

FROM (
SELECT ARI_REC_ID,DER_MAX_THERAPY_END_DATE
FROM
  (SELECT AP.ARI_REC_ID,
    AP.RECORD_ID,
    AP.RANK_ORDER ,
    'D'
    ||AP.RANK_ORDER
    ||': '
    ||
	CASE WHEN APT.DER_MAX_THERAPY IS NULL 
	THEN '-'
	ELSE UPPER(APT.DER_MAX_THERAPY)
	END AS DER_MAX_THERAPY_END_DATE
  FROM (select ARI_REC_ID,
    RECORD_ID,
    RANK_ORDER,DRUGCHARACTERIZATION,
	row_number() over (partition by ARI_REC_ID order by CDC_OPERATION_TIME desc) rank
	FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where 
		ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
    and CDC_OPERATION_TYPE IN ('I','U') 
	)AP LEFT JOIN
    (SELECT dgth_ARI_REC_ID,dgth_FK_AD_REC_ID AS SEQ_PRODUCT,
	CASE
       WHEN dgth_DRUGENDDATEFMT IS NULL  THEN TO_CHAR((dgth_DRUGENDDATE),'DD-MON-YYYY')
       WHEN dgth_DRUGENDDATEFMT in (0,102)  THEN TO_CHAR((dgth_DRUGENDDATE),'DD-MON-YYYY')
       WHEN dgth_DRUGENDDATEFMT in (1,602)  THEN TO_CHAR((dgth_DRUGENDDATE),'YYYY')
       WHEN dgth_DRUGENDDATEFMT in (2,610)  THEN TO_CHAR((dgth_DRUGENDDATE),'MON-YYYY')
       WHEN dgth_DRUGENDDATEFMT in (3,4,5,6,7,8,9,204,611,203)       THEN TO_CHAR((dgth_DRUGENDDATE),'DD-MON-YYYY')
     END DER_MAX_THERAPY
    FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY
    WHERE dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
	and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
	AND 
	(dgth_ARI_REC_ID,dgth_FK_AD_REC_ID,dgth_DRUGENDDATE) IN
		(select LS_DB_DRUG_THERAPY.dgth_ARI_REC_ID,
			LS_DB_DRUG_THERAPY.dgth_FK_AD_REC_ID,	
			MAX(LS_DB_DRUG_THERAPY.dgth_DRUGENDDATE) As MAX_END_THERAPY_DATE
			FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY 
			where dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
            and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')		
		group by 1,2
      )
	  and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
    ) APT ON  AP.DRUGCHARACTERIZATION IN ('1','3')
  AND AP.ARI_REC_ID        =APT.dgth_ARI_REC_ID
  AND AP.RECORD_ID   =APT.SEQ_PRODUCT
  where rank=1 and AP.ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
   AND
  AP.ARI_REC_ID||'-'||AP.RECORD_ID NOT IN
    (select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED)
  )
ORDER BY ARI_REC_ID,
  RANK_ORDER) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.ari_rec_id	
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
;

--DER_TIME_OFF_DRUG_NORMAL


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_TIME_OFF_DRUG_NORMAL=LS_DB_DRUG_THERAPY_TMP.DER_TIME_OFF_DRUG_NORMAL   

FROM (SELECT distinct ARI_REC_ID,SEQ_REACT,
LISTAGG(DER_TIME_OFF_DRUG_NORM,'\r\n')within group (ORDER BY AUTO_RANK) AS DER_TIME_OFF_DRUG_NORMAL

FROM (
SELECT R.ARI_REC_ID ,
	  R.RECORD_ID AS SEQ_REACT,
	  T.AUTO_RANK,
	  'D'
	  || T.AUTO_RANK
	  || ': '
	  ||NVL(CASE
        WHEN R.REACTSTARTDATE      IS NULL
        OR T.MAX_END_THERAPY_DATE IS NULL
        THEN NULL
        WHEN R.REACTSTARTDATEFMT IN ( 610,602)
        THEN NULL
        WHEN datediff(DAY, date_trunc('DAY',T.MAX_END_THERAPY_DATE), date_trunc('DAY',R.REACTSTARTDATE)) < 0
        THEN ( SUBSTRING(CAST( datediff(DAY, date_trunc('DAY',T.MAX_END_THERAPY_DATE), date_trunc('DAY',R.REACTSTARTDATE)) AS VARCHAR), 1,5))
        ELSE ( SUBSTRING(CAST( datediff(DAY, date_trunc('DAY',T.MAX_END_THERAPY_DATE), date_trunc('DAY',R.REACTSTARTDATE)) AS VARCHAR), 1,4))
      END,'-') AS DER_TIME_OFF_DRUG_NORM
		FROM (select RECORD_ID,ARI_REC_ID,REACTSTARTDATE,REACTSTARTDATEFMT,row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank 
											FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_REACTION
											where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U') 
										) R,
		  (SELECT A.ARI_REC_ID ,
			A.RECORD_ID,A.RANK_ORDER as AUTO_RANK,
			MAX(B.END_THERAPY_DATE) MAX_END_THERAPY_DATE
			
		  FROM
			(SELECT APT.dgth_ARI_REC_ID,
			  APT.SEQ_PRODUCT,
			  APTS.dgth_RECORD_ID AS SEQ_THERAPY,
			  APTS.dgth_DRUGENDDATE AS END_THERAPY_DATE
			FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY APTS,
			  (SELECT dgth_ARI_REC_ID,
				dgth_FK_AD_REC_ID AS SEQ_PRODUCT,
				MAX(dgth_RECORD_ID) SEQ_THERAPY
			  FROM
				$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY
			  WHERE dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
              and dgth_DRUGENDDATEFMT NOT IN ( 610,602) and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
			  GROUP BY 1,2
			  ) APT
			WHERE APTS.dgth_ARI_REC_ID   =APT.dgth_ARI_REC_ID
			AND APTS.dgth_FK_AD_REC_ID=APT.SEQ_PRODUCT
			AND APTS.dgth_RECORD_ID=APT.SEQ_THERAPY
			AND APTS.dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
			AND APTS.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
			) B ,
			(select RECORD_ID,ARI_REC_ID,DRUGCHARACTERIZATION,RANK_ORDER,row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank 
											FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG
											where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U') 
										) A 
		  WHERE A.ARI_REC_ID      =B.dgth_ARI_REC_ID (+)
		  AND A.RECORD_ID   =B.SEQ_PRODUCT (+)
		  AND A.DRUGCHARACTERIZATION  IN ('1','3')
		  AND A.rank=1
		  AND A.ARI_REC_ID||'-'||A.RECORD_ID NOT IN
			(select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_UNBLINDED)
			
		  GROUP BY A.ARI_REC_ID,
		  A.RECORD_ID,
		  A.RANK_ORDER
		  ) T
		WHERE  T.ARI_REC_ID      =R.ARI_REC_ID and R.rank=1
		
	ORDER BY R.ARI_REC_ID,
	  T.AUTO_RANK
	  )
	  
GROUP BY ARI_REC_ID,SEQ_REACT
) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.ari_rec_id	
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
;



UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_THERAPY_START_DATE=LS_DB_DRUG_THERAPY_TMP.DER_THERAPY_START_DATE   
,LS_DB_DRUG_THERAPY.DER_THERAPY_END_DATE=LS_DB_DRUG_THERAPY_TMP.DER_THERAPY_END_DATE
FROM (
select dgth_ari_rec_id,
case  when  dgth_DRUGSTARTDATE_NF IS NOT NULL THEN UPPER(dgth_DRUGSTARTDATE_NF)
	  when  dgth_DRUGSTARTDATEFMT is null  then null
	  when  dgth_DRUGSTARTDATEFMT in ('0','7','8','9','102')  then UPPER(to_char(dgth_DRUGSTARTDATE,'DD-MON-YYYY'))
	  when  dgth_DRUGSTARTDATEFMT in ('1','602')  then UPPER(to_char(dgth_DRUGSTARTDATE,'YYYY'))
	  when  dgth_DRUGSTARTDATEFMT in ('2','610')  then UPPER(to_char(dgth_DRUGSTARTDATE,'MON-YYYY'))
	--  when  DRUGSTARTDATEFMT in ('3','204')  then UPPER(to_char(DRUGSTARTDATE,'DD-MON-YYYY'))
	 -- when  DRUGSTARTDATEFMT in ('4','204')  then UPPER(to_char(DRUGSTARTDATE,'DD-MON-YYYY hh24'))
	  when  dgth_DRUGSTARTDATEFMT in ('5','203')  then UPPER(to_char(dgth_DRUGSTARTDATE,'DD-MON-YYYY hh24:mi'))
  	  when  dgth_DRUGSTARTDATEFMT in ('6','204')  then UPPER(to_char(dgth_DRUGSTARTDATE,'DD-MON-YYYY'))
	  when  dgth_DRUGSTARTDATEFMT in ('6','611')  then UPPER(to_char(dgth_DRUGSTARTDATE,'DD-MON-YYYY'))
end DER_THERAPY_START_DATE,
case  when  dgth_DRUGENDDATE_NF IS NOT NULL THEN UPPER(dgth_DRUGENDDATE_NF)
	  when  dgth_DRUGENDDATEFMT is null  then null
	  when  dgth_DRUGENDDATEFMT in ('0','7','8','9','102')  then UPPER(to_char(dgth_DRUGENDDATE,'DD-MON-YYYY'))
	  when  dgth_DRUGENDDATEFMT in  ('1','602')  then UPPER(to_char(dgth_DRUGENDDATE,'YYYY'))
	  when  dgth_DRUGENDDATEFMT in ('2','610')  then UPPER(to_char(dgth_DRUGENDDATE,'MON-YYYY'))
--	  when  dgth_DRUGENDDATEFMT in ('3','204')  then UPPER(to_char(DRUGENDDATE,'DD-MON-YYYY'))
	--  when  DRUGENDDATEFMT in ('4','204')  then UPPER(to_char(DRUGENDDATE,'DD-MON-YYYY hh24'))
	  when  dgth_DRUGENDDATEFMT in ('5','203')  then UPPER(to_char(dgth_DRUGENDDATE,'DD-MON-YYYY hh24:mi'))
  	  when  dgth_DRUGENDDATEFMT in ('6','204')  then UPPER(to_char(dgth_DRUGENDDATE,'DD-MON-YYYY'))
	  when  dgth_DRUGENDDATEFMT in ('6','611')  then UPPER(to_char(dgth_DRUGENDDATE,'DD-MON-YYYY'))
end DER_THERAPY_END_DATE

FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY where dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.dgth_ari_rec_id	
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
;


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_THERAPY_PERIOD_CONCAT=LS_DB_DRUG_THERAPY_TMP.DER_THERAPY_PERIOD_CONCAT   

FROM (SELECT 
ARI_REC_ID,SEQ_PRODUCT,LISTAGG(DER_THERAPY_PERIOD_CONCAT,' | ')within group (order by SEQ_THERAPY) AS DER_THERAPY_PERIOD_CONCAT
FROM
(
SELECT 
A.ARI_REC_ID,
A.SEQ_PRODUCT,
CASE WHEN A.THERPAY_DATE = '-' AND A.DURATION = '-' THEN '-'
ELSE A.THERPAY_DATE ||chr(10)||A.DURATION 
END As DER_THERAPY_PERIOD_CONCAT,
MIN(A.SEQ_THERAPY) AS SEQ_THERAPY
FROM
(
SELECT
APT.ARI_REC_ID,
APT.SEQ_THERAPY,
APT.SEQ_PRODUCT,
CASE 
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NULL AND APT.END_THERAPY_DATE IS NULL AND 
END_THERAPY_DATE_NF  IS NULL THEN '-'
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NULL AND 
APT.END_THERAPY_DATE IS NOT NULL AND END_THERAPY_DATE_NF  IS NULL THEN '-' ||' to '||APT.END_THERAPY_DATE
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NOT NULL AND 
APT.END_THERAPY_DATE IS NOT NULL AND END_THERAPY_DATE_NF  IS NULL THEN START_THERAPY_DATE_NF ||' to '||APT.END_THERAPY_DATE
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NULL AND 
APT.END_THERAPY_DATE IS  NULL AND END_THERAPY_DATE_NF  IS NOT NULL THEN '-' ||' to '||END_THERAPY_DATE_NF
WHEN APT.START_THERAPY_DATE IS NOT  NULL AND START_THERAPY_DATE_NF IS NULL AND 
 APT.END_THERAPY_DATE IS  NULL  AND END_THERAPY_DATE_NF  IS NULL THEN APT.START_THERAPY_DATE ||' to '|| '-'
 WHEN APT.START_THERAPY_DATE IS NOT  NULL AND START_THERAPY_DATE_NF IS NULL AND 
 APT.END_THERAPY_DATE IS  NULL  AND END_THERAPY_DATE_NF  IS NOT NULL THEN APT.START_THERAPY_DATE ||' to '|| END_THERAPY_DATE_NF
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NOT NULL AND 
 APT.END_THERAPY_DATE IS  NULL  AND END_THERAPY_DATE_NF  IS NULL THEN  START_THERAPY_DATE_NF ||' to '|| '-'
WHEN APT.START_THERAPY_DATE IS NULL AND START_THERAPY_DATE_NF IS NOT NULL AND 
 APT.END_THERAPY_DATE IS  NULL  AND END_THERAPY_DATE_NF  IS NOT NULL THEN  START_THERAPY_DATE_NF ||' to '|| END_THERAPY_DATE_NF
ELSE APT.START_THERAPY_DATE ||' to '||APT.END_THERAPY_DATE
END THERPAY_DATE,
CASE WHEN APT.THERAPY_DURATION IS NULL AND DC.DECODE IS NULL THEN '-'
WHEN APT.THERAPY_DURATION IS NULL AND DC.DECODE IS NOT NULL THEN '-' ||' '||DC.DECODE
WHEN APT.THERAPY_DURATION IS NOT NULL AND DC.DECODE IS NULL THEN APT.THERAPY_DURATION ||' '|| '-'
ELSE APT.THERAPY_DURATION ||' '||DC.DECODE
END DURATION

FROM
 (
SELECT
	DISTINCT dgth_ARI_REC_ID ARI_REC_ID,
	dgth_FK_AD_REC_ID AS SEQ_PRODUCT,
	dgth_RECORD_ID AS SEQ_THERAPY,
	CASE
       WHEN dgth_DRUGSTARTDATEFMT IS NULL  THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-Mon-YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (0,102)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-Mon-YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (1,602)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'YYYY')
       WHEN dgth_DRUGSTARTDATEFMT in (2,610)  THEN TO_CHAR((dgth_DRUGSTARTDATE),'Mon-YYYY')
       --WHEN DRUGSTARTDATEFMT IN(3,4,5,6,7,8,9)
	   WHEN dgth_DRUGSTARTDATEFMT in (3,4,5,6,7,8,9,204,611,203) THEN TO_CHAR((dgth_DRUGSTARTDATE),'DD-Mon-YYYY')
     END START_THERAPY_DATE,
	CASE WHEN dgth_DRUGENDDATEFMT IS NULL  THEN TO_CHAR((dgth_DRUGENDDATE),'DD-Mon-YYYY')
       WHEN dgth_DRUGENDDATEFMT in (0,102) THEN TO_CHAR((dgth_DRUGENDDATE),'DD-Mon-YYYY')
       WHEN dgth_DRUGENDDATEFMT in (1,602) THEN TO_CHAR((dgth_DRUGENDDATE),'YYYY')
       WHEN dgth_DRUGENDDATEFMT in (2,610) THEN TO_CHAR((dgth_DRUGENDDATE),'Mon-YYYY')
       --WHEN DRUGENDDATEFMT IN(3,4,5,6,7,8,9)
	   WHEN dgth_DRUGENDDATEFMT in (3,4,5,6,7,8,9,204,611,203) THEN TO_CHAR((dgth_DRUGENDDATE),'DD-Mon-YYYY')
     END END_THERAPY_DATE ,
	 
	dgth_DRUGSTARTDATE_NF AS START_THERAPY_DATE_NF,
	dgth_DRUGENDDATE_NF AS END_THERAPY_DATE_NF,
	dgth_DRUGADMINDURATION AS THERAPY_DURATION,
	dgth_DRUGADMINDURATIONUNIT AS THERAPY_DURATION_UNIT
FROM
	$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY
    where dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
		and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')

 	) APT
	LEFT OUTER JOIN (select CODE,DECODE from 
							(
								SELECT distinct LSMV_CODELIST_CODE.CODE ,LSMV_CODELIST_DECODE.DECODE 
								,row_number() over(partition by LSMV_CODELIST_NAME.CODELIST_ID,LSMV_CODELIST_CODE.CODE,LSMV_CODELIST_DECODE.LANGUAGE_CODE 
												order by LSMV_CODELIST_NAME.CDC_OPERATION_TIME  DESC,LSMV_CODELIST_CODE.CDC_OPERATION_TIME DESC,LSMV_CODELIST_DECODE.CDC_OPERATION_TIME DESC) rank


                                                                                      FROM
                                                                                      (
                                                                                                     SELECT RECORD_ID,CODELIST_ID,CDC_OPERATION_TIME,ROW_NUMBER() OVER ( PARTITION BY RECORD_ID ORDER BY CDC_OPERATION_TIME DESC) RANK
                                                                                                     FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_CODELIST_NAME WHERE codelist_id IN ('15')
                                                                                      ) LSMV_CODELIST_NAME JOIN
                                                                                      (
                                                                                                     SELECT RECORD_ID,      CODE,   FK_CL_NAME_REC_ID,CDC_OPERATION_TIME              ,ROW_NUMBER() OVER ( PARTITION BY RECORD_ID ORDER BY CDC_OPERATION_TIME DESC) RANK
                                                                                                     FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_CODELIST_CODE
                                                                                      ) LSMV_CODELIST_CODE  ON LSMV_CODELIST_NAME.RECORD_ID=LSMV_CODELIST_CODE.FK_CL_NAME_REC_ID
                                                                                      AND LSMV_CODELIST_NAME.RANK=1 AND LSMV_CODELIST_CODE.RANK=1
                                                                                      JOIN 
                                                                                      (
                                                                                                     SELECT RECORD_ID,LANGUAGE_CODE, DECODE,            FK_CL_CODE_REC_ID              ,CDC_OPERATION_TIME,ROW_NUMBER() OVER ( PARTITION BY RECORD_ID ORDER BY CDC_OPERATION_TIME DESC) RANK
                                                                                                     FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_CODELIST_DECODE where LANGUAGE_CODE='en'
                                                                                      ) LSMV_CODELIST_DECODE ON LSMV_CODELIST_CODE.RECORD_ID = LSMV_CODELIST_DECODE.FK_CL_CODE_REC_ID
                                                                                      AND LSMV_CODELIST_DECODE.RANK=1) where rank=1 
					) DC
	 ON APT.THERAPY_DURATION_UNIT=DC.CODE
	 ORDER BY
	 APT.ari_rec_id,
	APT.SEQ_PRODUCT,
	APT.SEQ_THERAPY
)A
where DER_THERAPY_PERIOD_CONCAT IS NOT NULL
GROUP BY  
A.ari_rec_id,
A.SEQ_PRODUCT,
CASE WHEN A.THERPAY_DATE = '-' AND A.DURATION = '-' THEN '-'
ELSE A.THERPAY_DATE ||chr(10)||A.DURATION 
END 
) final_out
Group by 	ARI_REC_ID,SEQ_PRODUCT
) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.ari_rec_id	
	and LS_DB_DRUG_THERAPY.dgth_FK_AD_REC_ID=LS_DB_DRUG_THERAPY_TMP.SEQ_PRODUCT
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM'); 




UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY   
SET LS_DB_DRUG_THERAPY.DER_TREATMENT_DURATION_NORMAL=COALESCE(LS_DB_DRUG_THERAPY_TMP.DER_TREATMENT_DURATION_NORMAL , LS_DB_DRUG_THERAPY_TMP.DURATION_ROUND )

FROM (
select  
	ARI_REC_ID,
	SEQ_PRODUCT,
	SEQ_REACT,
	ceil(MAX(DURATION)) DURATION_ROUND,
	cast
	(case when
		ROUND(MAX(to_date(to_char(END_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy'))-(MIN(to_date(to_char(START_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy')))) >=0 then 
		ROUND(MAX(to_date(to_char(END_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy'))-(MIN(to_date(to_char(START_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy'))))
	when
		ROUND(MAX(to_date(to_char(END_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy'))-(MIN(to_date(to_char(START_THERAPY_DATE,'dd-mm-yyyy'),'dd-mm-yyyy'))))<0 then
	null
	end as integer) DER_TREATMENT_DURATION_NORMAL
from
(SELECT
	APT.ARI_REC_ID,
	APT.SEQ_PRODUCT,
	AR.SEQ_REACT,
	case when APT.END_THERAPY_DATE_PRECISION not in (1,2,610,602) then APT.END_THERAPY_DATE else null end END_THERAPY_DATE,
	case when APT.START_THERAPY_DATE_PRECISION not in (1,2,610,602) then APT.START_THERAPY_DATE else null end START_THERAPY_DATE,
	case	when	APT.THERAPY_DURATION_UNIT in ('804')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('803')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) * 7 as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('802')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) * 30 as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('801')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) * 365 as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('805')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) / 24 as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('806')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) * 0.000694444 as numeric)
			when	APT.THERAPY_DURATION_UNIT in ('807')	then	cast (regexp_replace(APT.THERAPY_DURATION, '[a-zA-Z]',null) * 0.0000115740666667 as numeric)
			else	cast (null as numeric)
	end 	DURATION
FROM
	(SELECT
	DISTINCT dgth_ARI_REC_ID ARI_REC_ID,
	dgth_FK_AD_REC_ID AS SEQ_PRODUCT,
	dgth_RECORD_ID AS SEQ_THERAPY,
	dgth_DRUGSTARTDATEFMT START_THERAPY_DATE_PRECISION,
	dgth_DRUGSTARTDATE START_THERAPY_DATE,
	dgth_DRUGENDDATEFMT END_THERAPY_DATE_PRECISION,
	dgth_DRUGENDDATE END_THERAPY_DATE,
	dgth_DRUGSTARTDATE_NF AS START_THERAPY_DATE_NF,
	dgth_DRUGENDDATE_NF AS END_THERAPY_DATE_NF,
	dgth_DRUGADMINDURATION AS THERAPY_DURATION,
	dgth_DRUGADMINDURATIONUNIT AS THERAPY_DURATION_UNIT
FROM
	$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY
    where dgth_ARI_REC_ID in (select ari_rec_id from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC)
		and EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')

	)	APT,
	(select RECORD_ID as SEQ_PRODUCT,ARI_REC_ID,DRUGCHARACTERIZATION,RANK_ORDER,row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank 
											FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG
											where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U') 
	) 	AP,
	(
	SELECT
		ARI_REC_ID ,
		RECORD_ID AS SEQ_REACT,
		row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank
	FROM
	$$STG_DB_NAME.$$LSDB_RPL.LSMV_REACTION 
	where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY_CASE_QFC) 
	AND CDC_OPERATION_TYPE IN ('I','U')
	) AR	
WHERE 
	AP.DRUGCHARACTERIZATION IN ('1','3') AND ap.rank=1
	--AND AP.PRODUCT_TYPE='01'
	AND APT.ARI_REC_ID=AP.ARI_REC_ID
	AND APT.SEQ_PRODUCT=AP.SEQ_PRODUCT
	AND APT.ARI_REC_ID=AR.ARI_REC_ID AND AR.rank=1
)
GROUP BY 
	ARI_REC_ID,
	SEQ_PRODUCT,
	SEQ_REACT
) LS_DB_DRUG_THERAPY_TMP
    WHERE LS_DB_DRUG_THERAPY.dgth_ari_rec_id = LS_DB_DRUG_THERAPY_TMP.ari_rec_id	
	and LS_DB_DRUG_THERAPY.dgth_FK_AD_REC_ID=LS_DB_DRUG_THERAPY_TMP.SEQ_PRODUCT
	AND LS_DB_DRUG_THERAPY.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM');




UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL
SET LOAD_END_TS = current_timestamp,
LOAD_TS=(select max(LOAD_TS) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_THERAPY),
LOAD_STATUS='Completed'
where target_table_name='LS_DB_DRUG_THERAPY_DER'
and LOAD_STATUS = 'In Progress'
and LOAD_START_TS=(select max(LOAD_START_TS) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRUG_THERAPY_DER'
and LOAD_STATUS = 'In Progress') ;	
 


 RETURN 'LS_DB_DRUG_THERAPY_DER Update completed';

EXCEPTION
  WHEN OTHER THEN
    LET LINE := SQLCODE || ': ' || SQLERRM;
UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL set ERROR_DETAILS=:line,LOAD_STATUS = 'Error' WHERE target_table_name='LS_DB_DRUG_THERAPY_DER'
and LOAD_STATUS = 'In Progress'
;



END;
$$
;	

/*

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_THERAPY
  WAREHOUSE = EXTRASMALL
  Schedule = '15 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY_DER();
END;
$$
;

ALTER TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_THERAPY RESUME; 
 
 
 */
 
 
 
 
 
 