
-- alter table $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS add column DER_TIME_OFF_DRUG_DAYS text;


/*
delete from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where TARGET_TABLE_NAME='LS_DB_DRUG_REACT_LISTEDNESS_DER'
call $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS_DER()

select * from LS_DB_DRUG_REACT_LISTEDNESS limit 100

*/

-- USE SCHEMA $$TGT_DB_NAME.$$LSDB_TRANSFM;
CREATE OR REPLACE PROCEDURE $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS_DER()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
DECLARE

CURRENT_TS_VAR TIMESTAMP;

BEGIN 

CURRENT_TS_VAR := CURRENT_TIMESTAMP();




/*
ALTER TABLE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS ADD COLUMN DER_TIME_OFF_DRUG_DAYS TEXT;
*/




insert into $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG (ROW_WID,TARGET_TABLE_NAME,PARAM_NAME)

select ROW_WID,TARGET_TABLE_NAME,PARAM_NAME from 
(select (select max( ROW_WID) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)+1 ROW_WID,'LS_DB_DRUG_REACT_LISTEDNESS_DER' AS TARGET_TABLE_NAME,'CDC_EXTRACT_TS_LB' PARAM_NAME
 union all select (select max( ROW_WID) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)+2,'LS_DB_DRUG_REACT_LISTEDNESS_DER','CDC_EXTRACT_TS_UB'
) where TARGET_TABLE_NAME not in (select TARGET_TABLE_NAME from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG)
;

-- select * from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where TARGET_TABLE_NAME='LS_DB_DRUG_REACT_LISTEDNESS_DER'

INSERT INTO $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL(ROW_WID,FUNCTIONAL_AREA,ENTITY_NAME,TARGET_TABLE_NAME,LOAD_TS,LOAD_START_TS,LOAD_END_TS,
REC_READ_CNT,REC_PROCESSED_CNT,ERROR_REC_CNT,ERROR_DETAILS,LOAD_STATUS,CHANGED_REC_SET
)
SELECT (select nvl(max(row_wid)+1,1) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRUG_REACT_LISTEDNESS_DER'),
	'LSRA','Case','LS_DB_DRUG_REACT_LISTEDNESS_DER',null,:CURRENT_TS_VAR,null,null,null,null,null,'In Progress',null;


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= nvl((SELECT LOAD_TS from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL 
						WHERE TARGET_TABLE_NAME='LS_DB_DRUG_REACT_LISTEDNESS_DER' 
						AND LOAD_STATUS = 'Completed' ORDER BY ROW_WID DESC limit 1),to_timestamp('1900-01-01','YYYY-MM-DD'))
WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_REACT_LISTEDNESS_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_LB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;


UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= (select max(load_ts) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS)
WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_REACT_LISTEDNESS_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_UB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;

DROP TABLE IF EXISTS $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_QFC;
CREATE TEMPORARY TABLE  $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_QFC AS
select distinct ARI_REC_ID
FROM 
	$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS 
	
	where load_ts > (SELECT PARAM_VALUE FROM 
$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_REACT_LISTEDNESS_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_LB')  and

load_ts <=  (SELECT PARAM_VALUE FROM 
$$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME = 'LS_DB_DRUG_REACT_LISTEDNESS_DER'
AND PARAM_NAME='CDC_EXTRACT_TS_UB') 
AND LS_DB_DRUG_REACT_LISTEDNESS.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
;	



/*( select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_UNBLINDED
		)*/


DROP TABLE IF EXISTS $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_UNBLINDED;
CREATE TEMPORARY TABLE  $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_UNBLINDED AS
select LSMV_DRUG.ARI_REC_ID||'-'||AD.SEQ_PRODUCT AS UNBLINDED_REC
				from 
				(
				SELECT LSMV_DRUG.ARI_REC_ID,
					BLINDED_PRODUCT_REC_ID,
					row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank
				FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_SAFETY_MASTER_CASE_QFC)
				AND   CDC_OPERATION_TYPE IN ('I','U') 
				) LSMV_DRUG 
				JOIN
				(
				SELECT LSMV_DRUG.ARI_REC_ID,
					LSMV_DRUG.RECORD_ID AS SEQ_PRODUCT,
					row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank
				FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_SAFETY_MASTER_CASE_QFC)
				AND   CDC_OPERATION_TYPE IN ('I','U') 
				) AD
				ON LSMV_DRUG.ARI_REC_ID              = AD.ARI_REC_ID
				AND LSMV_DRUG.BLINDED_PRODUCT_REC_ID = AD.SEQ_PRODUCT
				AND LSMV_DRUG.rank=1 AND AD.rank=1

;




UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS   
SET LS_DB_DRUG_REACT_LISTEDNESS.DER_TIME_OFF_DRUG_DAYS=LS_DB_DRUG_REACT_LISTEDNESS_TMP.DER_TIME_OFF_DRUG_DAYS
FROM (


SELECT  ARI_REC_ID , RECORD_ID
         ,LISTAGG('D' || AUTO_RANK  || ': ' ||DER_TIME_OFF_DRUG_DAYS,'\r\n')within group (order by AUTO_RANK) AS DER_TIME_OFF_DRUG_DAYS 
FROM
(

   SELECT  R.ARI_REC_ID , R.RECORD_ID,
         NVL(CASE WHEN   R.REACTSTARTDATE IS NULL or T.MIN_END_THERAPY_DATE IS NULL THEN NULL
				WHEN   R.REACTSTARTDATEFMT  IN ( 610,602)  THEN NULL
        WHEN   datediff(DAY, date_trunc('DAY',R.REACTSTARTDATE ), date_trunc('DAY',T.MIN_END_THERAPY_DATE)) < 0  
          THEN ( SUBSTRING(CAST( datediff(DAY, date_trunc('DAY',R.REACTSTARTDATE ), date_trunc('DAY',T.MIN_END_THERAPY_DATE)) as VARCHAR), 1,5)) 
		ELSE ( SUBSTRING(CAST( datediff(DAY, date_trunc('DAY',R.REACTSTARTDATE ), date_trunc('DAY',T.MIN_END_THERAPY_DATE))  as VARCHAR), 1,4))  
		END,'-') AS DER_TIME_OFF_DRUG_DAYS 
		,T.AUTO_RANK AS AUTO_RANK
	
		FROM (select RECORD_ID,ARI_REC_ID,REACTSTARTDATE,REACTSTARTDATEFMT
				,row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank 
											FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_REACTION
											where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U') 
			 ) R, 
		(
		SELECT A.ARI_REC_ID , A.RECORD_ID,MIN(B.END_THERAPY_DATE) MIN_END_THERAPY_DATE,A.AUTO_RANK FROM 
		(select ARI_REC_ID,SEQ_PRODUCT,DRUGENDDATE As END_THERAPY_DATE FROM
				(
					SELECT ARI_REC_ID,FK_AD_REC_ID AS SEQ_PRODUCT,DRUGENDDATE,DRUGENDDATEFMT
							,ROW_NUMBER () over(PARTITION BY ARI_REC_ID,FK_AD_REC_ID order by CDC_OPERATION_TIME desc) rank 
						FROM
						$$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG_THERAPY  where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U')
				) As LSMV_DRUG_THERAPY	WHERE rank=1 and DRUGENDDATEFMT NOT IN ( 610,602)
		) B , 
		(select RECORD_ID,ARI_REC_ID,DRUGCHARACTERIZATION,RANK_ORDER As AUTO_RANK
			,row_number() over (partition by RECORD_ID order by CDC_OPERATION_TIME desc) rank 
		FROM $$STG_DB_NAME.$$LSDB_RPL.LSMV_DRUG
		where ARI_REC_ID in (select  ARI_REC_ID from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_QFC) AND CDC_OPERATION_TYPE IN ('I','U') 
		) A 
		WHERE A.ARI_REC_ID=B.ARI_REC_ID (+)
		AND A.RECORD_ID=B.SEQ_PRODUCT (+)
		AND A.DRUGCHARACTERIZATION IN ('1','3')
		AND A.RANK=1
		
		AND  A.ARI_REC_ID||'-'||A.RECORD_ID  NOT  IN
					(select UNBLINDED_REC from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS_CASE_UNBLINDED)
			
         GROUP BY A.ARI_REC_ID , A.RECORD_ID,A.AUTO_RANK
		 ) T
         WHERE T.ARI_REC_ID=R.ARI_REC_ID
         AND R.RANK=1
	) final_out 		 
group by  ARI_REC_ID , RECORD_ID ) LS_DB_DRUG_REACT_LISTEDNESS_TMP
    WHERE LS_DB_DRUG_REACT_LISTEDNESS.ARI_REC_ID = LS_DB_DRUG_REACT_LISTEDNESS_TMP.ARI_REC_ID	
	AND LS_DB_DRUG_REACT_LISTEDNESS.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM');




UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL
SET LOAD_END_TS = current_timestamp,
LOAD_TS=(select max(LOAD_TS) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DRUG_REACT_LISTEDNESS),
LOAD_STATUS='Completed'
where target_table_name='LS_DB_DRUG_REACT_LISTEDNESS_DER'
and LOAD_STATUS = 'In Progress'
and LOAD_START_TS=(select max(LOAD_START_TS) from $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRUG_REACT_LISTEDNESS_DER'
and LOAD_STATUS = 'In Progress') ;	




 RETURN 'LS_DB_DRUG_REACT_LISTEDNESS_DER Update completed';

EXCEPTION
  WHEN OTHER THEN
    LET LINE := SQLCODE || ': ' || SQLERRM;
UPDATE $$TGT_DB_NAME.$$LSDB_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL set ERROR_DETAILS=:line,LOAD_STATUS = 'Error' WHERE target_table_name='LS_DB_DRUG_REACT_LISTEDNESS_DER'
and LOAD_STATUS = 'In Progress'
;



END;
$$
;	

/*

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_LISTEDNESS
  WAREHOUSE = EXTRASMALL
  Schedule = '15 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS_DER();
END;
$$
;

ALTER TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_LISTEDNESS RESUME; 


*/




















