
CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_RECURRENCE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_RECURRENCE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SERIOUS_EVENTS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SERIOUS_EVENTS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_TASKS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_TASKS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_WF_NOTES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_WF_NOTES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_LOCAL_REACTION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_LOCAL_REACTION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_AE_CASE_TAG
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_AE_CASE_TAG();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SAFETY_LATENESS_ASSESSMENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SAFETY_LATENESS_ASSESSMENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_LOCAL_LABELLING
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_LOCAL_LABELLING();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PRODUCT_LABEL_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PRODUCT_LABEL_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ASYNC_WORKFLOW_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ASYNC_WORKFLOW_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REQUESTERS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REQUESTERS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ST_LABELLED_PROD_EVENTS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ST_LABELLED_PROD_EVENTS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PATIENT_PAST_DRUG
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT_PAST_DRUG();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_JPN_PRODUCT_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_JPN_PRODUCT_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_AE_SENDER_RECEIVER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_AE_SENDER_RECEIVER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PROD_ACTIVE_SUB_FORM
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PROD_ACTIVE_SUB_FORM();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_E2B_CASE_EXPORT_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_E2B_CASE_EXPORT_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DISTRIBUTION_FORMAT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DISTRIBUTION_FORMAT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_SUPPORT_DOC
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_SUPPORT_DOC();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_CASE_QUES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_CASE_QUES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WORKFLOW
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WORKFLOW();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LOCAL_LABELING
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LOCAL_LABELING();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_EMAIL_INTAKE_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_EMAIL_INTAKE_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_INBOUND_DOCUMENT_DETAILS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_INBOUND_DOCUMENT_DETAILS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_EMAIL_INTAKE_RPT_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_EMAIL_INTAKE_RPT_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE_HEALTH_RELATEDNESS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE_HEALTH_RELATEDNESS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_APPROVAL_INDICATIONS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_APPROVAL_INDICATIONS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_INGREDIENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_INGREDIENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_CASUALTY_ASSESSMENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_CASUALTY_ASSESSMENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_E2B_SUBMISSIONS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_E2B_SUBMISSIONS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_CAPA
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_CAPA();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SOURCE_DOCS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SOURCE_DOCS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_LOCAL_APPROVAL
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_LOCAL_APPROVAL();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SOURCE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SOURCE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SAFETY_CORRESPONDENCE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SAFETY_CORRESPONDENCE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_J12_STUDIES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_J12_STUDIES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PARENT_PAST_DRUG
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PARENT_PAST_DRUG();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PROD_INDICATION_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PROD_INDICATION_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_RESEARCH_RPT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_RESEARCH_RPT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_FLAGS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_FLAGS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LEBELED_MAPPED_COUNTY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LEBELED_MAPPED_COUNTY();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE_DEVICE_PROB_EVAL
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE_DEVICE_PROB_EVAL();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PARTNER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PARTNER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_THERAPY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY_DER();
END;
$$
;


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_E2B_IMPORT_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_E2B_IMPORT_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ACCOUNTS_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ACCOUNTS_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_NARRATIVE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_NARRATIVE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LANG_REDUCTED
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LANG_REDUCTED();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PERSON
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PERSON();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WF_ASSIGNMENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WF_ASSIGNMENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_CASE_SERIES_DETAILS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_CASE_SERIES_DETAILS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DLIST
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DLIST();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REPORTDUPLICATE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REPORTDUPLICATE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SAFETY_MASTER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SAFETY_MASTER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ACCOUNTS_SERIES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ACCOUNTS_SERIES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUPPORT_DOC
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUPPORT_DOC();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WF_INSTANCE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WF_INSTANCE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE_IDENTIFIER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE_IDENTIFIER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_STUDY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_STUDY();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PROD_APPROVAL_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PROD_APPROVAL_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_QUALITY_CHECK
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_QUALITY_CHECK();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_AER_CLINICAL_CLASSIFICATION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_AER_CLINICAL_CLASSIFICATION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_CASE_DETAILS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_CASE_DETAILS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_CORRESPONDENCE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_CORRESPONDENCE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_TEST
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_TEST();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_AER_ADDITIONAL_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_AER_ADDITIONAL_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LINKED_REPORT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LINKED_REPORT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PATIENT_PARENT_MED_HIST
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT_PARENT_MED_HIST();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SIMILAR_PRODUCTS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SIMILAR_PRODUCTS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE_THERAPY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE_THERAPY();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_HEALTH_DAMAGE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_HEALTH_DAMAGE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_RELATEDNESS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_RELATEDNESS();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_RELATEDNESS_DER();
END;
$$
;


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PREGNANCY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PREGNANCY();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_CASE_REACTION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_CASE_REACTION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PROD_INGREDIENT_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PROD_INGREDIENT_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_STUDY_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_STUDY_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PRODUCT_THERAPEUTIC_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PRODUCT_THERAPEUTIC_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PRD_CHARACTERISTIC
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PRD_CHARACTERISTIC();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PATIENT_MED_HIST_EPISODE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT_MED_HIST_EPISODE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SUBMISSION_CASE_PRODUCT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SUBMISSION_CASE_PRODUCT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_INDICATION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_INDICATION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_LOT_NUMBERS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_LOT_NUMBERS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REACTION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REACTION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_LISTEDNESS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS_DER();
END;
$$
;


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_IMRDF_EVALUATION
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_IMRDF_EVALUATION();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PRODUCT_LIB
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PRODUCT_LIB();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_CODELIST_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_CODELIST_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_JPN_REVIEW
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_JPN_REVIEW();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_NOTES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_NOTES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PATIENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REPORTER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REPORTER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LITERATURE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LITERATURE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WF_NOTES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WF_NOTES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SENDER_DIAGNOSIS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SENDER_DIAGNOSIS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_AGX_ANG_HISTORY
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_AGX_ANG_HISTORY();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_COMPONENT
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_COMPONENT();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_APPROVAL
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_APPROVAL();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DOCUMENT_STORE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DOCUMENT_STORE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_MESSAGE_INFM_AUTH
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_MESSAGE_INFM_AUTH();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ST_BATCH_SUB_QUEUE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ST_BATCH_SUB_QUEUE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_EVENT_GROUP
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_EVENT_GROUP();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REACT_VACCINE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REACT_VACCINE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_ACTIVITY_LOG
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_ACTIVITY_LOG();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LINKED_AE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LINKED_AE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_ADDITIONAL_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_ADDITIONAL_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_VERBATIM_TERMS
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_VERBATIM_TERMS();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_RISK_FACTOR
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_RISK_FACTOR();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SIMILAR_INCIDENT_DEVICE
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SIMILAR_INCIDENT_DEVICE();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DEVICE_PROBLEM
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DEVICE_PROBLEM();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WF_TRACKER
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WF_TRACKER();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_LOT_BATCH_INFO
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_LOT_BATCH_INFO();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_COMPONENT_PROCEDURES
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_COMPONENT_PROCEDURES();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PRODDEVICE_UDI
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PRODDEVICE_UDI();


CREATE OR REPLACE TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG();


 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_MESSAGE_INFM_AUTH
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_MESSAGE_INFM_AUTH();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_MESSAGE_INFM_AUTH_DER();
END;
$$
;



 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_THERAPY
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_THERAPY_DER();
END;
$$
;


 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_LISTEDNESS
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_LISTEDNESS_DER();
END;
$$
;

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_DRUG_REACT_RELATEDNESS
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_RELATEDNESS();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_DRUG_REACT_RELATEDNESS_DER();
END;
$$
;

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_PATIENT
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_PATIENT_DER();
END;
$$
;

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_REACTION
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REACTION();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_REACTION_DER();
END;
$$
;

 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SAFETY_MASTER
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SAFETY_MASTER();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SAFETY_MASTER_DER();
END;
$$
;


 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_SOURCE
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SOURCE();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_SOURCE_DER();
END;
$$
;


 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_TEST
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_TEST();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_TEST_DER();
END;
$$
;


 CREATE or replace TASK $$TGT_DB_NAME.$$LSDB_TRANSFM.TSK_LS_DB_WORKFLOW
  WAREHOUSE = EXTRASMALL
  Schedule = '200 minute'
AS
EXECUTE IMMEDIATE $$
DECLARE
    id int;
BEGIN
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WORKFLOW();
  CALL $$TGT_DB_NAME.$$LSDB_TRANSFM.PRC_LS_DB_WORKFLOW_DER();
END;
$$
;







