create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_SUBSTANCE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_SUBSTANCE from (select $1 :substance_code, $1 :substance_name, $1 :dictionary_version, $1 :inactive_flag, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :substance_chinese, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl_substance/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_ATC_CODE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_ATC_CODE from (select $1 :record_id, $1 :atc_code, $1 :atc_level, $1 :text, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_atc_code/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_KDD_CODE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_KDD_CODE from (select $1 :record_id, $1 :whodd_code, $1 :korean_standard_product_code, $1 :marketing_authorizaton_holder, $1 :pharmaceutical_form, $1 :strength, $1 :dictionary_version, $1 :user_modified, $1 :date_modified, $1 :user_created, $1 :date_created, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_link_kdd_code/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.INFORMATICA_CDC_RECOVERY auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.INFORMATICA_CDC_RECOVERY from (select $1 :task_id, $1 :type, $1 :schema_name, $1 :table_name, $1 :cycle_number, $1 :sequence, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/informatica_cdc_recovery/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL from (select $1 :drl_code, $1 :tradename, $1 :designation, $1 :name_source, $1 :mfr_code, $1 :quarter_introduced, $1 :preferred_code, $1 :dictionary_version, $1 :inactive_flag, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :tradename_chinese, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_ENG auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_ENG from (select $1 :record_id, $1 :maintenance_seq, $1 :jpn_drug_code, $1 :product_name_eng, $1 :jan_flag, $1 :inn_flag, $1 :not_used, $1 :eng_maintenance_yymm, $1 :maintenance_flag, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_jdd_eng/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_COUNTRY auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_COUNTRY from (select $1 :record_id, $1 :country_code, $1 :country_name, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_country/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_DRUG_INGREDIENT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_DRUG_INGREDIENT from (select $1 :preferred_code, $1 :substance_code, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl_drug_ingredient/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_RELATIONS auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_RELATIONS from (select $1 :smq_code_child, $1 :smq_code_parent, $1 :smq_meddra_version, $1 :child_med_version, $1 :language_code, $1 :record_id, $1 :dbid, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_smq_cmq_relations/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_ATC_CODES auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_ATC_CODES from (select $1 :atc_code, $1 :decode, $1 :atc_level, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :decode_chinese, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl_atc_codes/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_JPN auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_JPN from (select $1 :record_id, $1 :jpn_drug_code, $1 :gen_use_class, $1 :dosage_route_code, $1 :dosage_route, $1 :basic_name_code, $1 :product_name, $1 :prdouct_name_2, $1 :generic_name, $1 :generic_name_2, $1 :manufacturer_code, $1 :manufacturer_name, $1 :form_code, $1 :drug_code_class1, $1 :maintenance_seq, $1 :maintenance_flag, $1 :maintenance_yymm, $1 :drug_code_class2, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_jdd_jpn/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PHARMACEUTICAL_PRODUCT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PHARMACEUTICAL_PRODUCT from (select $1 :record_id, $1 :pharmproduct_id, $1 :pharmaceutical_form, $1 :route_of_administration, $1 :medicinal_prod_id, $1 :number_of_ingredients, $1 :term_date_created, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_pharmaceutical_product/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_DRUG_ATC_RELATION auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_DRUG_ATC_RELATION from (select $1 :preferred_code, $1 :atc_code, $1 :quarter_amended, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl_drug_atc_relation/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLGT_HLT_COMP auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLGT_HLT_COMP from (select $1 :hlgt_code, $1 :hlt_code, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_hlgt_hlt_comp/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PRODUCT_TYPE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PRODUCT_TYPE from (select $1 :record_id, $1 :prodtype_id, $1 :text, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_product_type/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_INGREDIENT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_INGREDIENT from (select $1 :record_id, $1 :ingredient_id, $1 :term_date_created, $1 :substance_id, $1 :quantity, $1 :quantity2, $1 :unit, $1 :pharmproduct_id, $1 :medicinal_prod_id, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_ingredient/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_THERAPEUTIC_GROUP auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_THERAPEUTIC_GROUP from (select $1 :record_id, $1 :therapgroup_id, $1 :atc_code, $1 :term_date_created, $1 :official_atc_code, $1 :medicinal_prod_id, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_therapeutic_group/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_SOC_TERM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_SOC_TERM from (select $1 :soc_code, $1 :soc_name, $1 :soc_abbrev, $1 :soc_whoart_code, $1 :soc_harts_code, $1 :soc_costart_sym, $1 :soc_icd9_code, $1 :soc_icd9cm_code, $1 :soc_icd10_code, $1 :soc_jart_code, $1 :soc_kanji, $1 :soc_order, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :soc_name_cn, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_soc_term/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_SOC_HLGT_COMP auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_SOC_HLGT_COMP from (select $1 :soc_code, $1 :hlgt_code, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_soc_hlgt_comp/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_STRENGTH auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_STRENGTH from (select $1 :record_id, $1 :strength_id, $1 :text, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_strength/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_SUBSTANCE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_SUBSTANCE from (select $1 :record_id, $1 :substance_code, $1 :cas_number, $1 :language_code, $1 :substance_name, $1 :year_of_reference, $1 :reference_code, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_substance/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_MFR auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_DRL_MFR from (select $1 :mfr_code, $1 :name, $1 :country, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :name_chinese, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_drl_mfr/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_JDD_CODE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_JDD_CODE from (select $1 :record_id, $1 :whodd_code, $1 :jdd_code, $1 :dictionary_version, $1 :user_created, $1 :date_created, $1 :user_modified, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_link_jdd_code/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_MED_PRODUCT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_MED_PRODUCT from (select $1 :record_id, $1 :medicinal_prod_id, $1 :med_id, $1 :drug_record_number, $1 :sequence_number1, $1 :sequence_number2, $1 :sequence_number3, $1 :sequence_number4, $1 :generic, $1 :drug_name, $1 :name_specifier, $1 :marketing_auth_number, $1 :marketing_auth_date, $1 :marketing_auth_withdrawal_date, $1 :country, $1 :company, $1 :marketing_auth_holder, $1 :reference_code, $1 :source_country, $1 :year_of_reference, $1 :product_type, $1 :product_group, $1 :term_date_created, $1 :term_date_modified, $1 :dictionary_version, $1 :combined_code, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_med_product/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_ORGANIZATION auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_ORGANIZATION from (select $1 :record_id, $1 :organization_id, $1 :org_name, $1 :country_code, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_organization/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PHARMACEUTICAL_FORM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PHARMACEUTICAL_FORM from (select $1 :record_id, $1 :pharmform_id, $1 :text, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_pharmaceutical_form/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_KDD_INGREDIENT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_KDD_INGREDIENT from (select $1 :record_id, $1 :ingredient_code, $1 :ingredient_name_one, $1 :ingredient_name_zero, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_kdd_ingredient/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLGT_PREF_TERM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLGT_PREF_TERM from (select $1 :hlgt_code, $1 :hlgt_name, $1 :hlgt_whoart_code, $1 :hlgt_harts_code, $1 :hlgt_costart_sym, $1 :hlgt_icd9_code, $1 :hlgt_icd9cm_code, $1 :hlgt_icd10_code, $1 :hlgt_jart_code, $1 :hlgt_kanji, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :hlgt_name_cn, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_hlgt_pref_term/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_MD_HIERARCHY auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_MD_HIERARCHY from (select $1 :pt_code, $1 :hlt_code, $1 :hlgt_code, $1 :soc_code, $1 :pt_name, $1 :hlt_name, $1 :hlgt_name, $1 :soc_name, $1 :soc_abbrev, $1 :null_field, $1 :pt_soc_code, $1 :primary_soc_fg, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :pt_name_cn, $1 :hlgt_name_cn, $1 :hlt_name_cn, $1 :soc_name_cn, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_md_hierarchy/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PRODUCT_GROUP auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_PRODUCT_GROUP from (select $1 :record_id, $1 :productgroup_id, $1 :productgroup_name, $1 :date_recorded, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_product_group/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_TERMS_INFO auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_TERMS_INFO from (select $1 :smq_code, $1 :term_code, $1 :term_level, $1 :term_scope, $1 :term_status, $1 :term_addition_version, $1 :term_last_modified_version, $1 :smq_meddra_version, $1 :term_med_version, $1 :soc_code, $1 :term_category, $1 :term_weight, $1 :language_code, $1 :record_id, $1 :dbid, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_smq_cmq_terms_info/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_MEDPROD_SUBSTANCE auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_WHODDC_MEDPROD_SUBSTANCE from (select $1 :record_id, $1 :reference_code, $1 :medprod_reference, $1 :country_code, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_whoddc_medprod_substance/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_LIST auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_SMQ_CMQ_LIST from (select $1 :smq_code, $1 :smq_name, $1 :smq_name_j, $1 :smq_level, $1 :smq_description, $1 :smq_description_j, $1 :smq_note, $1 :smq_source, $1 :meddra_version, $1 :status, $1 :list_source, $1 :term_from, $1 :user_id, $1 :private_query_flag, $1 :smq_algorithm, $1 :language_code, $1 :portfolio_flag, $1 :approval_state, $1 :record_id, $1 :dbid, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_smq_cmq_list/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_PREF_TERM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_PREF_TERM from (select $1 :pt_code, $1 :pt_name, $1 :pt_soc_code, $1 :pt_whoart_code, $1 :pt_harts_code, $1 :pt_costart_sym, $1 :pt_icd9_code, $1 :pt_icd9cm_code, $1 :pt_icd10_code, $1 :pt_jart_code, $1 :null_field, $1 :pt_kanji, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :pt_name_cn, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_pref_term/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLT_PREF_COMP auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLT_PREF_COMP from (select $1 :hlt_code, $1 :pt_code, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_hlt_pref_comp/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_OTC auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_JDD_OTC from (select $1 :record_id, $1 :digit_code_2, $1 :classification1, $1 :digit_code_3, $1 :classification2, $1 :digit_code_12, $1 :product_name, $1 :manufacturer, $1 :dictionary_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_jdd_otc/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_LOW_LEVEL_TERM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_LOW_LEVEL_TERM from (select $1 :llt_code, $1 :llt_name, $1 :pt_code, $1 :llt_whoart_code, $1 :llt_harts_code, $1 :llt_costart_sym, $1 :llt_icd9_code, $1 :llt_icd9cm_code, $1 :llt_icd10_code, $1 :llt_currency, $1 :llt_jart_code, $1 :llt_kanji, $1 :llt_jcurr, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :llt_name_cn, $1 :llt_cncurr, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_low_level_term/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_KDD_CAS auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_LINK_KDD_CAS from (select $1 :record_id, $1 :cas_number, $1 :korean_substance_code, $1 :dictionary_version, $1 :user_modified, $1 :date_modified, $1 :user_created, $1 :date_created, $1 :spr_id, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_link_kdd_cas/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_KDD_PRODUCT auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_CC_KDD_PRODUCT from (select $1 :record_id, $1 :std_prod_code, $1 :product_name, $1 :company_name, $1 :manufacturer_type, $1 :etc_otc, $1 :main_ingredient, $1 :main_ingredient_no, $1 :approval_status, $1 :date_of_reg, $1 :reg_status, $1 :dictionary_version, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_cc_kdd_product/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
create or replace pipe ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLT_PREF_TERM auto_ingest=true as copy into ${stage_cntrl_db_name}.${stage_cntrl_schema_name}.LSMV_HLT_PREF_TERM from (select $1 :hlt_code, $1 :hlt_name, $1 :hlt_whoart_code, $1 :hlt_harts_code, $1 :hlt_costart_sym, $1 :hlt_icd9_code, $1 :hlt_icd9cm_code, $1 :hlt_icd10_code, $1 :hlt_jart_code, $1 :hlt_kanji, $1 :meddra_version, $1 :user_created, $1 :user_modified, $1 :date_created, $1 :date_modified, $1 :record_id, $1 :spr_id, $1 :hlt_name_cn, COALESCE($1 :Op,'I') , METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @${external_stage_name}/${lsmv_schema_anme}/lsmv_hlt_pref_term/ )
  ON_ERROR = CONTINUE
file_format = (type = 'parquet' compression = auto );
