
-- USE SCHEMA $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM;
CREATE OR REPLACE PROCEDURE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL()
RETURNS VARCHAR NOT NULL

LANGUAGE SQL
AS
$$

DECLARE

CURRENT_TS_VAR TIMESTAMP;

BEGIN 

CURRENT_TS_VAR := CURRENT_TIMESTAMP();



INSERT INTO $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL(ROW_WID,FUNCTIONAL_AREA,ENTITY_NAME,TARGET_TABLE_NAME,LOAD_TS,LOAD_START_TS,LOAD_END_TS,
REC_READ_CNT,REC_PROCESSED_CNT,ERROR_REC_CNT,ERROR_DETAILS,LOAD_STATUS,CHANGED_REC_SET
)
SELECT (select nvl(max(row_wid)+1,1) from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRL'),
	'LSRA','Case','LS_DB_DRL',null,:CURRENT_TS_VAR,null,null,null,null,null,'In Progress',null;


UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= nvl((SELECT LOAD_START_TS from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL WHERE TARGET_TABLE_NAME='LS_DB_DRL' AND LOAD_STATUS = 'Completed' ORDER BY ROW_WID DESC limit 1),to_timestamp('1900-01-01','YYYY-MM-DD'))
WHERE TARGET_TABLE_NAME = 'LS_DB_DRL'
AND PARAM_NAME='CDC_EXTRACT_TS_LB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;

UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG
SET PARAM_VALUE= :CURRENT_TS_VAR
WHERE TARGET_TABLE_NAME = 'LS_DB_DRL'
AND PARAM_NAME='CDC_EXTRACT_TS_UB'
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
;





DROP TABLE IF EXISTS $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LSMV_DRL_DELETION_TMP;
CREATE TEMPORARY TABLE  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LSMV_DRL_DELETION_TMP  As select RECORD_ID,'lsmv_drl' AS TABLE_NAME FROM $$STG_CNTRL_DB_NAME.$$LSDB_RPL.lsmv_drl WHERE CDC_OPERATION_TYPE IN ('D') ;
DROP TABLE IF EXISTS $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP;
CREATE TEMPORARY TABLE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP  AS  WITH 
LSMV_CASE_NO_SUBSET as
 (
 
select DISTINCT RECORD_ID record_id, 0 common_parent_key   FROM $$STG_CNTRL_DB_NAME.$$LSDB_RPL.lsmv_drl WHERE CDC_OPERATION_TIME >(SELECT PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LS_DB_DRL' AND PARAM_NAME='CDC_EXTRACT_TS_LB')
	AND CDC_OPERATION_TIME<= (SELECT PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LS_DB_DRL' AND PARAM_NAME='CDC_EXTRACT_TS_UB')
UNION 

select DISTINCT 0 record_id, 0 common_parent_key  FROM $$STG_CNTRL_DB_NAME.$$LSDB_RPL.lsmv_drl WHERE CDC_OPERATION_TIME >(SELECT PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LS_DB_DRL' AND PARAM_NAME='CDC_EXTRACT_TS_LB')
	AND CDC_OPERATION_TIME<= (SELECT PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LS_DB_DRL' AND PARAM_NAME='CDC_EXTRACT_TS_UB')
)
 , lsmv_drl_SUBSET AS 
(
select * from 
    (SELECT  
    date_created  date_created,date_modified  date_modified,designation  designation,dictionary_version  dictionary_version,drl_code  drl_code,inactive_flag  inactive_flag,mfr_code  mfr_code,name_source  name_source,preferred_code  preferred_code,quarter_introduced  quarter_introduced,record_id  record_id,spr_id  spr_id,tradename  tradename,tradename_chinese  tradename_chinese,user_created  user_created,user_modified  user_modified,row_number() OVER ( PARTITION BY RECORD_ID,RECORD_ID ORDER BY CDC_OPERATION_TIME DESC ) REC_RANK
FROM 
$$STG_CNTRL_DB_NAME.$$LSDB_RPL.lsmv_drl
 WHERE  RECORD_ID IN (SELECT record_id FROM LSMV_CASE_NO_SUBSET) 
 AND RECORD_ID not in (SELECT RECORD_ID FROM  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LSMV_DRL_DELETION_TMP  WHERE TABLE_NAME='lsmv_drl')
  ) where REC_RANK=1 )
    SELECT DISTINCT  to_date(GREATEST(
NVL(lsmv_drl_SUBSET.DATE_MODIFIED ,TO_DATE('1900-01-01','YYYY-DD-MM'))
))
PROCESSING_DT 
,TO_DATE('9999-31-12','YYYY-DD-MM') EXPIRY_DATE,lsmv_drl_SUBSET.USER_CREATED CREATED_BY,lsmv_drl_SUBSET.DATE_CREATED CREATED_DT,:CURRENT_TS_VAR LOAD_TS,lsmv_drl_SUBSET.user_modified  ,lsmv_drl_SUBSET.user_created  ,lsmv_drl_SUBSET.tradename_chinese  ,lsmv_drl_SUBSET.tradename  ,lsmv_drl_SUBSET.spr_id  ,lsmv_drl_SUBSET.record_id  ,lsmv_drl_SUBSET.quarter_introduced  ,lsmv_drl_SUBSET.preferred_code  ,lsmv_drl_SUBSET.name_source  ,lsmv_drl_SUBSET.mfr_code  ,lsmv_drl_SUBSET.inactive_flag  ,lsmv_drl_SUBSET.drl_code  ,lsmv_drl_SUBSET.dictionary_version  ,lsmv_drl_SUBSET.designation  ,lsmv_drl_SUBSET.date_modified  ,lsmv_drl_SUBSET.date_created ,CONCAT( NVL(lsmv_drl_SUBSET.RECORD_ID,-1)) INTEGRATION_ID FROM lsmv_drl_SUBSET  WHERE 1=1  
;



UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL
SET REC_READ_CNT = (select count(LOAD_TS) from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP)
where target_table_name='LS_DB_DRL'
and LOAD_STATUS = 'In Progress'
and LOAD_START_TS=(select max(LOAD_START_TS) from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRL'
					and LOAD_STATUS = 'In Progress') 
; 

UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL   
SET LS_DB_DRL.user_modified = LS_DB_DRL_TMP.user_modified,LS_DB_DRL.user_created = LS_DB_DRL_TMP.user_created,LS_DB_DRL.tradename_chinese = LS_DB_DRL_TMP.tradename_chinese,LS_DB_DRL.tradename = LS_DB_DRL_TMP.tradename,LS_DB_DRL.spr_id = LS_DB_DRL_TMP.spr_id,LS_DB_DRL.record_id = LS_DB_DRL_TMP.record_id,LS_DB_DRL.quarter_introduced = LS_DB_DRL_TMP.quarter_introduced,LS_DB_DRL.preferred_code = LS_DB_DRL_TMP.preferred_code,LS_DB_DRL.name_source = LS_DB_DRL_TMP.name_source,LS_DB_DRL.mfr_code = LS_DB_DRL_TMP.mfr_code,LS_DB_DRL.inactive_flag = LS_DB_DRL_TMP.inactive_flag,LS_DB_DRL.drl_code = LS_DB_DRL_TMP.drl_code,LS_DB_DRL.dictionary_version = LS_DB_DRL_TMP.dictionary_version,LS_DB_DRL.designation = LS_DB_DRL_TMP.designation,LS_DB_DRL.date_modified = LS_DB_DRL_TMP.date_modified,LS_DB_DRL.date_created = LS_DB_DRL_TMP.date_created,
LS_DB_DRL.PROCESSING_DT = LS_DB_DRL_TMP.PROCESSING_DT ,
LS_DB_DRL.expiry_date    =LS_DB_DRL_TMP.expiry_date       ,
LS_DB_DRL.created_by     =LS_DB_DRL_TMP.created_by        ,
LS_DB_DRL.created_dt     =LS_DB_DRL_TMP.created_dt        ,
LS_DB_DRL.load_ts        =LS_DB_DRL_TMP.load_ts         
FROM 	$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP 
WHERE 	LS_DB_DRL.INTEGRATION_ID = LS_DB_DRL_TMP.INTEGRATION_ID
AND DECODE('YES',(SELECT CHAR_PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME='HISTORY_CONTROL'),
           LS_DB_DRL_TMP.PROCESSING_DT = LS_DB_DRL.PROCESSING_DT,1=1);


INSERT INTO $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL
(
processing_dt ,
expiry_date   ,
load_ts       ,
integration_id ,user_modified,
user_created,
tradename_chinese,
tradename,
spr_id,
record_id,
quarter_introduced,
preferred_code,
name_source,
mfr_code,
inactive_flag,
drl_code,
dictionary_version,
designation,
date_modified,
date_created)
SELECT 

processing_dt ,
expiry_date   ,
load_ts       ,
integration_id ,user_modified,
user_created,
tradename_chinese,
tradename,
spr_id,
record_id,
quarter_introduced,
preferred_code,
name_source,
mfr_code,
inactive_flag,
drl_code,
dictionary_version,
designation,
date_modified,
date_created
FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP TMP WHERE CONCAT(TMP.INTEGRATION_ID,'||',CASE WHEN 'YES'=(SELECT CHAR_PARAM_VALUE 
														FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG 
														WHERE TARGET_TABLE_NAME ='HISTORY_CONTROL' AND PARAM_NAME='KEEP_HISTORY') 
                                                        THEN TMP.PROCESSING_DT ELSE '9999-12-31' END ) 
									NOT IN (SELECT CONCAT(TGT.INTEGRATION_ID,'||',CASE WHEN 'YES'=(SELECT CHAR_PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='HISTORY_CONTROL' AND PARAM_NAME='KEEP_HISTORY') 
																				THEN TGT.PROCESSING_DT ELSE '9999-12-31' END) FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL TGT)
                                                                                ; 
COMMIT;



DELETE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL TGT
WHERE  ( record_id  in (SELECT RECORD_ID FROM  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LSMV_DRL_DELETION_TMP  WHERE TABLE_NAME='lsmv_drl')
)
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
AND 'NO'=(SELECT CHAR_PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='HISTORY_CONTROL' AND PARAM_NAME='KEEP_HISTORY');

UPDATE  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL 
SET EXPIRY_DATE=CURRENT_DATE()-1
FROM 	$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP 
WHERE 	TO_DATE(LS_DB_DRL.PROCESSING_DT) < TO_DATE(LS_DB_DRL_TMP.PROCESSING_DT)
AND LS_DB_DRL.INTEGRATION_ID = LS_DB_DRL_TMP.INTEGRATION_ID
AND LS_DB_DRL.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
AND 'YES'=(SELECT CHAR_PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='HISTORY_CONTROL' AND PARAM_NAME='KEEP_HISTORY')	
;



UPDATE  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL TGT
SET 	TGT.EXPIRY_DATE=CURRENT_DATE()
WHERE 	 ( record_id  in (SELECT RECORD_ID FROM  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LSMV_DRL_DELETION_TMP  WHERE TABLE_NAME='lsmv_drl')
)
AND 	TGT.EXPIRY_DATE = TO_DATE('9999-31-12','YYYY-DD-MM')
--AND 'I' = (SELECT PARAM_NAME FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='LOAD_CONTROL')
AND 'YES'=(SELECT CHAR_PARAM_VALUE FROM $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_ETL_CONFIG WHERE TARGET_TABLE_NAME ='HISTORY_CONTROL' 
           AND PARAM_NAME='KEEP_HISTORY');

UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL
SET LOAD_END_TS = current_timestamp,
REC_PROCESSED_CNT=(select count(LOAD_TS) from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL where LOAD_TS= (select LOAD_TS from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP limit 1)),
LOAD_TS=(select LOAD_TS from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_TMP limit 1),
LOAD_STATUS='Completed'
where target_table_name='LS_DB_DRL'
and LOAD_STATUS = 'In Progress'
and LOAD_START_TS=(select max(LOAD_START_TS) from $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL where target_table_name='LS_DB_DRL'
and LOAD_STATUS = 'In Progress') ;
           
  RETURN 'LS_DB_DRL Load completed';

EXCEPTION
  WHEN OTHER THEN
    LET LINE := SQLCODE || ': ' || SQLERRM;
UPDATE $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DATA_PROCESSING_DTL_TBL set ERROR_DETAILS=:line, LOAD_STATUS = 'Error' WHERE target_table_name='LS_DB_DRL'
and LOAD_STATUS = 'In Progress'
;

  RETURN 'LS_DB_DRL not loaded due to etl error. please check LS_DB_DATA_PROCESSING_DTL_TBL for more details';
END;
$$
;



           
