CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_MEDDRA_ICD
WAREHOUSE =EXTRASMALL 
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_MEDDRA_ICD();


CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_ATC_CODES
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL_ATC_CODES();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_DRUG_ATC_RELATION
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL_DRUG_ATC_RELATION();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_MFR
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL_MFR();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_MD_HIERARCHY
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_MD_HIERARCHY();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_HLGT_PREF_TERM
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_HLGT_PREF_TERM();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_PREF_TERM
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_PREF_TERM();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_HLT_PREF_TERM
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_HLT_PREF_TERM();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_SOC_TERM
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_SOC_TERM();

CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_CC_SMQ_CMQ_LIST
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_CC_SMQ_CMQ_LIST();


CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_LOW_LEVEL_TERM
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_LOW_LEVEL_TERM();


CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_DRUG_INGREDIENT
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL_DRUG_INGREDIENT();


CREATE OR REPLACE TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_SUBSTANCE
WAREHOUSE =EXTRASMALL
Schedule = '200 minute'
as Call  $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.PRC_LS_DB_DRL_SUBSTANCE();







