CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_MEDDRA_ICD ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_MEDDRA_ICD SHOW_INITIAL_ROWS = TRUE;



CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL_ATC_CODES ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_ATC_CODES SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL_DRUG_ATC_RELATION ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_DRUG_ATC_RELATION SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL_MFR ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_MFR SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_MD_HIERARCHY ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_MD_HIERARCHY SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_HLGT_PREF_TERM ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_HLGT_PREF_TERM SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_PREF_TERM ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_PREF_TERM SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_HLT_PREF_TERM ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_HLT_PREF_TERM SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL SHOW_INITIAL_ROWS = TRUE;


CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_SOC_TERM ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_SOC_TERM SHOW_INITIAL_ROWS = TRUE;


CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_CC_SMQ_CMQ_LIST ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_CC_SMQ_CMQ_LIST SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_LOW_LEVEL_TERM ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_LOW_LEVEL_TERM SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL_DRUG_INGREDIENT ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_DRUG_INGREDIENT SHOW_INITIAL_ROWS = TRUE;

CREATE OR REPLACE STREAM 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.STRM_LS_DB_DRL_SUBSTANCE ON TABLE 
$$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.LS_DB_DRL_SUBSTANCE SHOW_INITIAL_ROWS = TRUE;










