/*
ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_MEDDRA_ICD RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_ATC_CODES  RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_DRUG_ATC_RELATION RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_MFR RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_MD_HIERARCHY RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_HLGT_PREF_TERM RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_PREF_TERM RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_HLT_PREF_TERM RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_SOC_TERM RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_CC_SMQ_CMQ_LIST RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_LOW_LEVEL_TERM RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_DRUG_INGREDIENT RESUME;

ALTER TASK $$TGT_CNTRL_DB_NAME.$$LSDB_CNTRL_TRANSFM.TSK_LS_DB_DRL_SUBSTANCE RESUME;

*/








